#include "my.h"

qk_tap_dance_action_t tap_dance_actions[] = {
    [MY_TD_Z_GRV] = ACTION_TAP_DANCE_DOUBLE(KC_Z, KC_GRV),
    [MY_TD_DOT_LBRC] = ACTION_TAP_DANCE_DOUBLE(KC_DOT, KC_LBRC),
    [MY_TD_SLASH_RBRC] = ACTION_TAP_DANCE_DOUBLE(KC_SLSH, KC_RBRC),
    [MY_TD_C_QUOT] = ACTION_TAP_DANCE_DOUBLE(KC_C, KC_QUOT),
};

